Repository Pro-Pofol/Pro-Pofol_Client, pull requests merged in 2024-06, with the labels that each got.

#33 Feature/#27 mypage
  next.config.mjs
  src/app/profile/LogoutButton.tsx
  src/app/profile/ProfileInfo.tsx
  src/app/profile/edit/ProfileEdit.tsx
  src/app/profile/edit/page.tsx
  src/app/profile/page.tsx
  src/assets/images/DefaultProfile.webp
  src/assets/images/index.ts
  src/assets/index.ts
  src/components/BackButton.tsx
  src/components/Button.tsx
  src/components/index.ts
  src/components/modal/SignupModal.tsx
  src/constants/index.ts
  src/constants/major.ts
  src/services/authLogin.ts
  src/services/getMe.ts
  src/utils/cookie.ts
  src/utils/index.ts
  src/utils/uploadFile.ts
Labels: UI, 기능

#37 지원서 자료 관련 api 연동
  src/app/application/ShowSection.tsx
  src/app/application/SideBar.tsx
  src/app/page.tsx
  src/components/ApplicationBox.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/SubTitleSection.tsx
  src/components/modal/ApplicationModal.tsx
  src/components/modal/BaseModal.tsx
  src/components/modal/TipModal.tsx
  src/components/modal/UploadSelectModal.tsx
  src/components/modal/index.ts
  src/constants/dummy.ts
  src/services/getUser.ts
  src/services/index.ts
  src/services/post/getApplicationData.ts
  src/services/post/index.ts
  src/services/post/postFile.ts
  src/services/tip/index.ts
  src/services/tip/postTip.ts
  src/types/applicationPreview.type.ts
  src/types/post/index.ts
  src/types/post/postSearch.type.ts
  src/types/post/uploadTip.type.ts
Labels: 기능

#38 FIX :: application search & signup
  src/app/application/EmptyDataSection.tsx
  src/app/application/ShowSection.tsx
  src/app/application/SideBar.tsx
  src/components/modal/SignupModal.tsx
  src/services/post/getApplicationData.ts
  src/types/authSignupType.ts
  src/types/post/postSearch.type.ts
Labels: 버그

#40 Feature/#27 :: 유저 정보 수정 연동 완료
  src/app/profile/ProfileInfo.tsx
  src/app/profile/[id]/page.tsx
  src/app/profile/edit/ProfileEdit.tsx
  src/services/index.ts
  src/services/profile/editProfile.ts
  src/types/userType.ts
Labels: 기능

#41 Feature/#27 :: 내가 공유한 지원서 & 팁 연동 완료
  src/app/profile/ProfileInfo.tsx
  src/app/profile/application/page.tsx
  src/app/profile/page.tsx
  src/app/profile/tip/page.tsx
  src/components/BackButton.tsx
Labels: 기능
