Repository Pro-Pofol/Pro-Pofol_Client, pull requests merged in 2024-05, with the labels that each got.

#17 application page publising
  src/app/application/Banner.tsx
  src/app/application/ShowSection.tsx
  src/app/application/SideBar.tsx
  src/app/application/SideSelect.tsx
  src/app/application/page.tsx
  src/app/main/Banner.tsx
  src/app/page.tsx
  src/assets/images/GradientImg.jpg
  src/assets/index.ts
  src/components/ApplicationBox.tsx
  src/components/Chip.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/Select.tsx
  src/components/SubTitleSection.tsx
  src/components/TipBox.tsx
  src/components/index.ts
  src/components/modal/ApplicationModal.tsx
  src/components/modal/BaseModal.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/SigninModal.tsx
  src/components/modal/index.ts
  tailwind.config.ts
Labels: UI, 기능

#21 Feature/#18 toast
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/assets/Check.tsx
  src/assets/Download.tsx
  src/assets/index.ts
  src/components/modal/ApplicationModal.tsx
  src/utils/index.ts
  src/utils/store/Provider.tsx
  src/utils/store/modules/index.ts
  src/utils/store/modules/toast.ts
  src/utils/store/store.ts
  src/utils/toast/Toaster.tsx
  src/utils/toast/toast.ts
  tailwind.config.ts
Labels: UI, 기능

#23 Feature/#15 :: Google auth 연동 완료
  package.json
  pnpm-lock.yaml
  public/images/Not.webp
  src/app/auth/facebook/login/route.ts
  src/app/auth/google/login/route.ts
  src/app/auth/kakao/login/route.ts
  src/app/auth/login/route.ts
  src/app/globals.css
  src/app/not-found.tsx
  src/app/signup/Signup.tsx
  src/app/signup/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/Select.tsx
  src/components/index.ts
  src/components/modal/LoginModal.tsx
  src/components/modal/SigninModal.tsx
  src/components/modal/SignupModal.tsx
  src/components/modal/index.ts
  src/services/authLogin.ts
  src/services/authSignup.ts
  src/services/getKakaoToken.ts
  src/services/index.ts
  src/services/interceptor.ts
  src/types/authKind.type.ts
  src/types/authSignupType.ts
  src/types/index.ts
  src/types/majorType.ts
  src/utils/cookie.ts
  src/utils/index.ts
  src/utils/loginRedirect.ts
Labels: 기능

#25 Feature/#15 :: Kakao auth 연동 완료
  src/app/auth/google/login/route.ts
  src/app/auth/kakao/login/route.ts
  src/components/modal/SignupModal.tsx
  src/services/authLogin.ts
  src/services/getKakaoToken.ts
Labels: 기능

#29 Feature/#15 :: 회원가입 후 재로그인 제거
  src/app/auth/facebook/login/route.ts
  src/app/auth/login/route.ts
  src/components/modal/SignupModal.tsx
  src/services/authSignup.ts
  src/utils/loginRedirect.ts
Labels: 기능

#30 application api 연동(미완)
  src/app/application/ShowSection.tsx
  src/app/application/SideBar.tsx
  src/app/application/page.tsx
  src/app/page.tsx
  src/components/ApplicationBox.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/modal/ApplicationModal.tsx
  src/services/index.ts
  src/services/interceptor.ts
  src/services/post/getRecommend.ts
  src/services/post/index.ts
  src/services/post/postFile.ts
  src/services/post/postLink.ts
  src/types/applicationFile.type.ts
  src/types/applicationPreview.type.ts
  src/types/index.ts
  src/types/majorType.ts
  src/types/post/index.ts
  src/types/post/postLink.type.ts
Labels: 기능

#31 Feature/#15 :: 마이페이지 퍼블리싱
  .prettierrc.json
  src/app/profile/application/page.tsx
  src/app/profile/edit/page.tsx
  src/app/profile/page.tsx
  src/app/profile/tip/page.tsx
  src/components/ApplicationBox.tsx
  src/components/Header.tsx
  src/components/TipBox.tsx
  src/constants/dummy.ts
  src/constants/index.ts
Labels: UI
